// The Env type and binding shapes are generated by `wrangler types` into
// worker-configuration.d.ts. We re-export the global `Cloudflare.Env`
// here so the rest of the worker keeps using `import type { Env } …`.
export type Env = Cloudflare.Env;

/** True when the worker should bypass its own caches and tell clients
 *  not to cache responses. */
export function cacheDisabled(env: Env): boolean {
  const v = env.CACHE_DISABLED;
  return v != null && v !== "" && v !== "0" && v.toLowerCase() !== "false";
}
